// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// standardize_cpu_cpp
List standardize_cpu_cpp(NumericMatrix data);
RcppExport SEXP _faissR_standardize_cpu_cpp(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(standardize_cpu_cpp(data));
    return rcpp_result_gen;
END_RCPP
}
// strip_self_neighbors_cpp
List strip_self_neighbors_cpp(IntegerMatrix indices, NumericMatrix distances);
RcppExport SEXP _faissR_strip_self_neighbors_cpp(SEXP indicesSEXP, SEXP distancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    rcpp_result_gen = Rcpp::wrap(strip_self_neighbors_cpp(indices, distances));
    return rcpp_result_gen;
END_RCPP
}
// validate_projection_knn_cpp
List validate_projection_knn_cpp(IntegerMatrix indices, NumericMatrix distances, int n_reference, int k);
RcppExport SEXP _faissR_validate_projection_knn_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP n_referenceSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< int >::type n_reference(n_referenceSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_projection_knn_cpp(indices, distances, n_reference, k));
    return rcpp_result_gen;
END_RCPP
}
// mean_neighbor_rank_error_cpp
double mean_neighbor_rank_error_cpp(IntegerMatrix high_indices, IntegerMatrix embed_indices, int k);
RcppExport SEXP _faissR_mean_neighbor_rank_error_cpp(SEXP high_indicesSEXP, SEXP embed_indicesSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type high_indices(high_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type embed_indices(embed_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_neighbor_rank_error_cpp(high_indices, embed_indices, k));
    return rcpp_result_gen;
END_RCPP
}
// majority_vote_knn_labels_cpp
IntegerVector majority_vote_knn_labels_cpp(IntegerMatrix embed_indices, IntegerVector labels, int k, int n_label_levels);
RcppExport SEXP _faissR_majority_vote_knn_labels_cpp(SEXP embed_indicesSEXP, SEXP labelsSEXP, SEXP kSEXP, SEXP n_label_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type embed_indices(embed_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_label_levels(n_label_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(majority_vote_knn_labels_cpp(embed_indices, labels, k, n_label_levels));
    return rcpp_result_gen;
END_RCPP
}
// batch_entropy_cpp
NumericVector batch_entropy_cpp(IntegerMatrix embed_indices, IntegerVector batch, int k, int n_batch_levels);
RcppExport SEXP _faissR_batch_entropy_cpp(SEXP embed_indicesSEXP, SEXP batchSEXP, SEXP kSEXP, SEXP n_batch_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type embed_indices(embed_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch(batchSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_batch_levels(n_batch_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_entropy_cpp(embed_indices, batch, k, n_batch_levels));
    return rcpp_result_gen;
END_RCPP
}
// sampled_pair_distances_cpp
NumericVector sampled_pair_distances_cpp(NumericMatrix x, IntegerVector a, IntegerVector b, int n_threads);
RcppExport SEXP _faissR_sampled_pair_distances_cpp(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sampled_pair_distances_cpp(x, a, b, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// knn_structure_score_cpp
Rcpp::NumericVector knn_structure_score_cpp(NumericMatrix layout, IntegerMatrix indices, Rcpp::IntegerVector keep, int preserve_k, Rcpp::IntegerVector labels, int n_label_levels);
RcppExport SEXP _faissR_knn_structure_score_cpp(SEXP layoutSEXP, SEXP indicesSEXP, SEXP keepSEXP, SEXP preserve_kSEXP, SEXP labelsSEXP, SEXP n_label_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type layout(layoutSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< int >::type preserve_k(preserve_kSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_label_levels(n_label_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_structure_score_cpp(layout, indices, keep, preserve_k, labels, n_label_levels));
    return rcpp_result_gen;
END_RCPP
}
// silhouette_score_cpp
double silhouette_score_cpp(NumericMatrix layout, Rcpp::IntegerVector labels);
RcppExport SEXP _faissR_silhouette_score_cpp(SEXP layoutSEXP, SEXP labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type layout(layoutSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labels(labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(silhouette_score_cpp(layout, labels));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_landmark_layout_cpp
NumericMatrix interpolate_landmark_layout_cpp(NumericMatrix landmark_layout, Rcpp::IntegerVector landmark_indices, IntegerMatrix projection_indices, NumericMatrix projection_distances, int n);
RcppExport SEXP _faissR_interpolate_landmark_layout_cpp(SEXP landmark_layoutSEXP, SEXP landmark_indicesSEXP, SEXP projection_indicesSEXP, SEXP projection_distancesSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type landmark_layout(landmark_layoutSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type landmark_indices(landmark_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type projection_indices(projection_indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type projection_distances(projection_distancesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_landmark_layout_cpp(landmark_layout, landmark_indices, projection_indices, projection_distances, n));
    return rcpp_result_gen;
END_RCPP
}
// select_low_confidence_rows_cpp
List select_low_confidence_rows_cpp(NumericVector confidence, IntegerVector landmark_indices, double fraction);
RcppExport SEXP _faissR_select_low_confidence_rows_cpp(SEXP confidenceSEXP, SEXP landmark_indicesSEXP, SEXP fractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type confidence(confidenceSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type landmark_indices(landmark_indicesSEXP);
    Rcpp::traits::input_parameter< double >::type fraction(fractionSEXP);
    rcpp_result_gen = Rcpp::wrap(select_low_confidence_rows_cpp(confidence, landmark_indices, fraction));
    return rcpp_result_gen;
END_RCPP
}
// project_embedding_knn_cpp
NumericMatrix project_embedding_knn_cpp(NumericMatrix reference_layout, IntegerMatrix projection_indices, NumericMatrix projection_distances);
RcppExport SEXP _faissR_project_embedding_knn_cpp(SEXP reference_layoutSEXP, SEXP projection_indicesSEXP, SEXP projection_distancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type reference_layout(reference_layoutSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type projection_indices(projection_indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type projection_distances(projection_distancesSEXP);
    rcpp_result_gen = Rcpp::wrap(project_embedding_knn_cpp(reference_layout, projection_indices, projection_distances));
    return rcpp_result_gen;
END_RCPP
}
// project_embedding_affine_cpp
List project_embedding_affine_cpp(NumericMatrix reference_data, NumericMatrix query_data, NumericMatrix reference_layout, IntegerMatrix projection_indices, NumericMatrix projection_distances, int max_neighbors, double ridge, double max_extrapolation);
RcppExport SEXP _faissR_project_embedding_affine_cpp(SEXP reference_dataSEXP, SEXP query_dataSEXP, SEXP reference_layoutSEXP, SEXP projection_indicesSEXP, SEXP projection_distancesSEXP, SEXP max_neighborsSEXP, SEXP ridgeSEXP, SEXP max_extrapolationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type reference_data(reference_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type query_data(query_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type reference_layout(reference_layoutSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type projection_indices(projection_indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type projection_distances(projection_distancesSEXP);
    Rcpp::traits::input_parameter< int >::type max_neighbors(max_neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< double >::type max_extrapolation(max_extrapolationSEXP);
    rcpp_result_gen = Rcpp::wrap(project_embedding_affine_cpp(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation));
    return rcpp_result_gen;
END_RCPP
}
// project_embedding_affine_parallel_cpp
List project_embedding_affine_parallel_cpp(NumericMatrix reference_data, NumericMatrix query_data, NumericMatrix reference_layout, IntegerMatrix projection_indices, NumericMatrix projection_distances, int max_neighbors, double ridge, double max_extrapolation, int n_threads);
RcppExport SEXP _faissR_project_embedding_affine_parallel_cpp(SEXP reference_dataSEXP, SEXP query_dataSEXP, SEXP reference_layoutSEXP, SEXP projection_indicesSEXP, SEXP projection_distancesSEXP, SEXP max_neighborsSEXP, SEXP ridgeSEXP, SEXP max_extrapolationSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type reference_data(reference_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type query_data(query_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type reference_layout(reference_layoutSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type projection_indices(projection_indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type projection_distances(projection_distancesSEXP);
    Rcpp::traits::input_parameter< int >::type max_neighbors(max_neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< double >::type max_extrapolation(max_extrapolationSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(project_embedding_affine_parallel_cpp(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// knn_graph_edges_cpp
List knn_graph_edges_cpp(IntegerMatrix indices, NumericMatrix distances, std::string weight_type, double prune, bool mutual);
RcppExport SEXP _faissR_knn_graph_edges_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP weight_typeSEXP, SEXP pruneSEXP, SEXP mutualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< double >::type prune(pruneSEXP);
    Rcpp::traits::input_parameter< bool >::type mutual(mutualSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_graph_edges_cpp(indices, distances, weight_type, prune, mutual));
    return rcpp_result_gen;
END_RCPP
}
// cugraph_available_cpp
bool cugraph_available_cpp();
RcppExport SEXP _faissR_cugraph_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cugraph_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// graph_cluster_cpp
List graph_cluster_cpp(IntegerMatrix indices, NumericMatrix distances, std::string method, std::string backend, std::string weight_type, double prune, bool mutual, int n_threads, int n_runs, double resolution, int n_iterations, int steps, int seed);
RcppExport SEXP _faissR_graph_cluster_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP weight_typeSEXP, SEXP pruneSEXP, SEXP mutualSEXP, SEXP n_threadsSEXP, SEXP n_runsSEXP, SEXP resolutionSEXP, SEXP n_iterationsSEXP, SEXP stepsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< double >::type prune(pruneSEXP);
    Rcpp::traits::input_parameter< bool >::type mutual(mutualSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type n_runs(n_runsSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_cluster_cpp(indices, distances, method, backend, weight_type, prune, mutual, n_threads, n_runs, resolution, n_iterations, steps, seed));
    return rcpp_result_gen;
END_RCPP
}
// graph_cluster_edges_cpp
List graph_cluster_edges_cpp(List edge_list, std::string method, std::string backend, int n_threads, int n_runs, double resolution, int n_iterations, int steps, int seed);
RcppExport SEXP _faissR_graph_cluster_edges_cpp(SEXP edge_listSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP n_threadsSEXP, SEXP n_runsSEXP, SEXP resolutionSEXP, SEXP n_iterationsSEXP, SEXP stepsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type edge_list(edge_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type n_runs(n_runsSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_cluster_edges_cpp(edge_list, method, backend, n_threads, n_runs, resolution, n_iterations, steps, seed));
    return rcpp_result_gen;
END_RCPP
}
// nn_cpp
List nn_cpp(NumericMatrix data, NumericMatrix points, int k, std::string method, bool square, bool sorted, double p, bool parallel, int cores, bool exclude_self);
RcppExport SEXP _faissR_nn_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP squareSEXP, SEXP sortedSEXP, SEXP pSEXP, SEXP parallelSEXP, SEXP coresSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    Rcpp::traits::input_parameter< bool >::type sorted(sortedSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cpp(data, points, k, method, square, sorted, p, parallel, cores, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nndescent_candidate_matrix_cpp
IntegerMatrix nndescent_candidate_matrix_cpp(IntegerMatrix indices, int n_sources, int n_neighbors);
RcppExport SEXP _faissR_nndescent_candidate_matrix_cpp(SEXP indicesSEXP, SEXP n_sourcesSEXP, SEXP n_neighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< int >::type n_sources(n_sourcesSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(nndescent_candidate_matrix_cpp(indices, n_sources, n_neighbors));
    return rcpp_result_gen;
END_RCPP
}
// nndescent_candidate_matrix_adaptive_cpp
IntegerMatrix nndescent_candidate_matrix_adaptive_cpp(IntegerMatrix indices, LogicalMatrix flags, int n_sources, int n_neighbors, bool use_reverse, bool active_only);
RcppExport SEXP _faissR_nndescent_candidate_matrix_adaptive_cpp(SEXP indicesSEXP, SEXP flagsSEXP, SEXP n_sourcesSEXP, SEXP n_neighborsSEXP, SEXP use_reverseSEXP, SEXP active_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type flags(flagsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sources(n_sourcesSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_reverse(use_reverseSEXP);
    Rcpp::traits::input_parameter< bool >::type active_only(active_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(nndescent_candidate_matrix_adaptive_cpp(indices, flags, n_sources, n_neighbors, use_reverse, active_only));
    return rcpp_result_gen;
END_RCPP
}
// nndescent_candidate_matrix_adaptive_subset_cpp
List nndescent_candidate_matrix_adaptive_subset_cpp(IntegerMatrix indices, LogicalMatrix flags, int n_sources, int n_neighbors, bool use_reverse);
RcppExport SEXP _faissR_nndescent_candidate_matrix_adaptive_subset_cpp(SEXP indicesSEXP, SEXP flagsSEXP, SEXP n_sourcesSEXP, SEXP n_neighborsSEXP, SEXP use_reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type flags(flagsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sources(n_sourcesSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_reverse(use_reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(nndescent_candidate_matrix_adaptive_subset_cpp(indices, flags, n_sources, n_neighbors, use_reverse));
    return rcpp_result_gen;
END_RCPP
}
// landmark_candidate_knn_cpp
List landmark_candidate_knn_cpp(NumericMatrix data, IntegerMatrix projection_indices, int k, int bucket_cols, int query_cols, bool parallel, int cores);
RcppExport SEXP _faissR_landmark_candidate_knn_cpp(SEXP dataSEXP, SEXP projection_indicesSEXP, SEXP kSEXP, SEXP bucket_colsSEXP, SEXP query_colsSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type projection_indices(projection_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type bucket_cols(bucket_colsSEXP);
    Rcpp::traits::input_parameter< int >::type query_cols(query_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(landmark_candidate_knn_cpp(data, projection_indices, k, bucket_cols, query_cols, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// landmark_candidate_knn_subset_cpp
List landmark_candidate_knn_subset_cpp(NumericMatrix data, IntegerMatrix projection_indices, IntegerVector query_rows, int k, int bucket_cols, int query_cols, bool parallel, int cores);
RcppExport SEXP _faissR_landmark_candidate_knn_subset_cpp(SEXP dataSEXP, SEXP projection_indicesSEXP, SEXP query_rowsSEXP, SEXP kSEXP, SEXP bucket_colsSEXP, SEXP query_colsSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type projection_indices(projection_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type query_rows(query_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type bucket_cols(bucket_colsSEXP);
    Rcpp::traits::input_parameter< int >::type query_cols(query_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(landmark_candidate_knn_subset_cpp(data, projection_indices, query_rows, k, bucket_cols, query_cols, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// landmark_projection_knn_approx_cpp
List landmark_projection_knn_approx_cpp(NumericMatrix landmarks, NumericMatrix queries, int k, int n_projections, int window, int seed, bool parallel, int cores);
RcppExport SEXP _faissR_landmark_projection_knn_approx_cpp(SEXP landmarksSEXP, SEXP queriesSEXP, SEXP kSEXP, SEXP n_projectionsSEXP, SEXP windowSEXP, SEXP seedSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type landmarks(landmarksSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_projections(n_projectionsSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(landmark_projection_knn_approx_cpp(landmarks, queries, k, n_projections, window, seed, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// nndescent_self_knn_cpp
List nndescent_self_knn_cpp(NumericMatrix data, int k, int pool_size, int n_iters, int max_candidates, int n_random_projections, int seed, bool parallel, int cores, std::string metric);
RcppExport SEXP _faissR_nndescent_self_knn_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP pool_sizeSEXP, SEXP n_itersSEXP, SEXP max_candidatesSEXP, SEXP n_random_projectionsSEXP, SEXP seedSEXP, SEXP parallelSEXP, SEXP coresSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type pool_size(pool_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_iters(n_itersSEXP);
    Rcpp::traits::input_parameter< int >::type max_candidates(max_candidatesSEXP);
    Rcpp::traits::input_parameter< int >::type n_random_projections(n_random_projectionsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(nndescent_self_knn_cpp(data, k, pool_size, n_iters, max_candidates, n_random_projections, seed, parallel, cores, metric));
    return rcpp_result_gen;
END_RCPP
}
// ivf_self_knn_cpp
List ivf_self_knn_cpp(NumericMatrix data, int k, int nlist, int nprobe, int seed, bool parallel, int cores);
RcppExport SEXP _faissR_ivf_self_knn_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP nlistSEXP, SEXP nprobeSEXP, SEXP seedSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nlist(nlistSEXP);
    Rcpp::traits::input_parameter< int >::type nprobe(nprobeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(ivf_self_knn_cpp(data, k, nlist, nprobe, seed, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// annoy_self_knn_cpp
List annoy_self_knn_cpp(NumericMatrix data, int k, int n_trees, int leaf_size, int search_k, int seed, bool parallel, int cores);
RcppExport SEXP _faissR_annoy_self_knn_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP n_treesSEXP, SEXP leaf_sizeSEXP, SEXP search_kSEXP, SEXP seedSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< int >::type leaf_size(leaf_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type search_k(search_kSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(annoy_self_knn_cpp(data, k, n_trees, leaf_size, search_k, seed, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// vptree_self_knn_cpp
List vptree_self_knn_cpp(NumericMatrix data, int k, bool parallel, int cores);
RcppExport SEXP _faissR_vptree_self_knn_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(vptree_self_knn_cpp(data, k, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// vptree_query_knn_cpp
List vptree_query_knn_cpp(NumericMatrix data, NumericMatrix points, int k, bool parallel, int cores);
RcppExport SEXP _faissR_vptree_query_knn_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(vptree_query_knn_cpp(data, points, k, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// grid2d_self_knn_cpp
List grid2d_self_knn_cpp(NumericMatrix data, int k, bool parallel, int cores, int bins_per_dim);
RcppExport SEXP _faissR_grid2d_self_knn_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP parallelSEXP, SEXP coresSEXP, SEXP bins_per_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type bins_per_dim(bins_per_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(grid2d_self_knn_cpp(data, k, parallel, cores, bins_per_dim));
    return rcpp_result_gen;
END_RCPP
}
// grid3d_self_knn_cpp
List grid3d_self_knn_cpp(NumericMatrix data, int k, bool parallel, int cores, int bins_per_dim);
RcppExport SEXP _faissR_grid3d_self_knn_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP parallelSEXP, SEXP coresSEXP, SEXP bins_per_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type bins_per_dim(bins_per_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(grid3d_self_knn_cpp(data, k, parallel, cores, bins_per_dim));
    return rcpp_result_gen;
END_RCPP
}
// candidate_knn_cpp
List candidate_knn_cpp(NumericMatrix data, NumericMatrix points, IntegerMatrix candidate_indices, int k, std::string method, bool square, bool exclude_self, bool parallel, int cores);
RcppExport SEXP _faissR_candidate_knn_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP candidate_indicesSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP squareSEXP, SEXP exclude_selfSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type candidate_indices(candidate_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(candidate_knn_cpp(data, points, candidate_indices, k, method, square, exclude_self, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// cuda_available_cpp
bool cuda_available_cpp();
RcppExport SEXP _faissR_cuda_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cuda_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// cuda_device_info_json_cpp
std::string cuda_device_info_json_cpp();
RcppExport SEXP _faissR_cuda_device_info_json_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cuda_device_info_json_cpp());
    return rcpp_result_gen;
END_RCPP
}
// nn_cuda_cpp
List nn_cuda_cpp(NumericMatrix data, NumericMatrix points, int k, bool square);
RcppExport SEXP _faissR_nn_cuda_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP squareSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cuda_cpp(data, points, k, square));
    return rcpp_result_gen;
END_RCPP
}
// landmark_candidate_knn_cuda_cpp
List landmark_candidate_knn_cuda_cpp(NumericMatrix data, IntegerMatrix projection_indices, int k, int bucket_cols, int query_cols);
RcppExport SEXP _faissR_landmark_candidate_knn_cuda_cpp(SEXP dataSEXP, SEXP projection_indicesSEXP, SEXP kSEXP, SEXP bucket_colsSEXP, SEXP query_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type projection_indices(projection_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type bucket_cols(bucket_colsSEXP);
    Rcpp::traits::input_parameter< int >::type query_cols(query_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(landmark_candidate_knn_cuda_cpp(data, projection_indices, k, bucket_cols, query_cols));
    return rcpp_result_gen;
END_RCPP
}
// row_candidate_knn_cuda_cpp
List row_candidate_knn_cuda_cpp(NumericMatrix data, IntegerMatrix candidate_indices, int k, std::string metric);
RcppExport SEXP _faissR_row_candidate_knn_cuda_cpp(SEXP dataSEXP, SEXP candidate_indicesSEXP, SEXP kSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type candidate_indices(candidate_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(row_candidate_knn_cuda_cpp(data, candidate_indices, k, metric));
    return rcpp_result_gen;
END_RCPP
}
// cuda_grid_self_knn_cpp
List cuda_grid_self_knn_cpp(NumericMatrix data, int k, int bins_per_dim);
RcppExport SEXP _faissR_cuda_grid_self_knn_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP bins_per_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type bins_per_dim(bins_per_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_grid_self_knn_cpp(data, k, bins_per_dim));
    return rcpp_result_gen;
END_RCPP
}
// cuvs_available_cpp
bool cuvs_available_cpp();
RcppExport SEXP _faissR_cuvs_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cuvs_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// cuvs_info_json_cpp
std::string cuvs_info_json_cpp();
RcppExport SEXP _faissR_cuvs_info_json_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cuvs_info_json_cpp());
    return rcpp_result_gen;
END_RCPP
}
// nn_cuvs_bruteforce_cpp
List nn_cuvs_bruteforce_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self);
RcppExport SEXP _faissR_nn_cuvs_bruteforce_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cuvs_bruteforce_cpp(data, points, k, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nn_cuvs_cagra_cpp
List nn_cuvs_cagra_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self, int graph_degree, int intermediate_graph_degree, int search_width, int itopk_size);
RcppExport SEXP _faissR_nn_cuvs_cagra_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP, SEXP graph_degreeSEXP, SEXP intermediate_graph_degreeSEXP, SEXP search_widthSEXP, SEXP itopk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type graph_degree(graph_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type intermediate_graph_degree(intermediate_graph_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type search_width(search_widthSEXP);
    Rcpp::traits::input_parameter< int >::type itopk_size(itopk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cuvs_cagra_cpp(data, points, k, exclude_self, graph_degree, intermediate_graph_degree, search_width, itopk_size));
    return rcpp_result_gen;
END_RCPP
}
// nn_cuvs_nndescent_self_cpp
List nn_cuvs_nndescent_self_cpp(NumericMatrix data, int k, int graph_degree, int intermediate_graph_degree, int max_iterations);
RcppExport SEXP _faissR_nn_cuvs_nndescent_self_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP graph_degreeSEXP, SEXP intermediate_graph_degreeSEXP, SEXP max_iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type graph_degree(graph_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type intermediate_graph_degree(intermediate_graph_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cuvs_nndescent_self_cpp(data, k, graph_degree, intermediate_graph_degree, max_iterations));
    return rcpp_result_gen;
END_RCPP
}
// nn_cuvs_ivf_flat_cpp
List nn_cuvs_ivf_flat_cpp(NumericMatrix data, NumericMatrix points, int k, int n_lists, int n_probes, bool exclude_self);
RcppExport SEXP _faissR_nn_cuvs_ivf_flat_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP n_listsSEXP, SEXP n_probesSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_lists(n_listsSEXP);
    Rcpp::traits::input_parameter< int >::type n_probes(n_probesSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cuvs_ivf_flat_cpp(data, points, k, n_lists, n_probes, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nn_cuvs_ivf_pq_cpp
List nn_cuvs_ivf_pq_cpp(NumericMatrix data, NumericMatrix points, int k, int n_lists, int n_probes, int pq_dim, int pq_bits, bool exclude_self);
RcppExport SEXP _faissR_nn_cuvs_ivf_pq_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP n_listsSEXP, SEXP n_probesSEXP, SEXP pq_dimSEXP, SEXP pq_bitsSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_lists(n_listsSEXP);
    Rcpp::traits::input_parameter< int >::type n_probes(n_probesSEXP);
    Rcpp::traits::input_parameter< int >::type pq_dim(pq_dimSEXP);
    Rcpp::traits::input_parameter< int >::type pq_bits(pq_bitsSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cuvs_ivf_pq_cpp(data, points, k, n_lists, n_probes, pq_dim, pq_bits, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// kmeans_cuvs_cpp
List kmeans_cuvs_cpp(NumericMatrix data, int centers, int max_iter, int n_init, double tol, int streaming_batch_size, bool kmeans_plus_plus);
RcppExport SEXP _faissR_kmeans_cuvs_cpp(SEXP dataSEXP, SEXP centersSEXP, SEXP max_iterSEXP, SEXP n_initSEXP, SEXP tolSEXP, SEXP streaming_batch_sizeSEXP, SEXP kmeans_plus_plusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_init(n_initSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type streaming_batch_size(streaming_batch_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type kmeans_plus_plus(kmeans_plus_plusSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans_cuvs_cpp(data, centers, max_iter, n_init, tol, streaming_batch_size, kmeans_plus_plus));
    return rcpp_result_gen;
END_RCPP
}
// faiss_available_cpp
bool faiss_available_cpp();
RcppExport SEXP _faissR_faiss_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(faiss_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// faiss_info_json_cpp
std::string faiss_info_json_cpp();
RcppExport SEXP _faissR_faiss_info_json_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(faiss_info_json_cpp());
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_flat_cpp
List nn_faiss_flat_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_flat_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_flat_cpp(data, points, k, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_flat_float32_cpp
List nn_faiss_flat_float32_cpp(SEXP data, SEXP points, int k, bool exclude_self, int n_threads, std::string metric, std::string distance_storage);
RcppExport SEXP _faissR_nn_faiss_flat_float32_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP, SEXP metricSEXP, SEXP distance_storageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_storage(distance_storageSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_flat_float32_cpp(data, points, k, exclude_self, n_threads, metric, distance_storage));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_ivf_cpp
List nn_faiss_ivf_cpp(NumericMatrix data, NumericMatrix points, int k, int nlist, int nprobe, std::string metric, std::string distance_output, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_ivf_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP nlistSEXP, SEXP nprobeSEXP, SEXP metricSEXP, SEXP distance_outputSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nlist(nlistSEXP);
    Rcpp::traits::input_parameter< int >::type nprobe(nprobeSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_output(distance_outputSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_ivf_cpp(data, points, k, nlist, nprobe, metric, distance_output, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_flat_ip_cpp
List nn_faiss_flat_ip_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_flat_ip_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_flat_ip_cpp(data, points, k, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_flat_normalized_ip_distance_cpp
List nn_faiss_flat_normalized_ip_distance_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_flat_normalized_ip_distance_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_flat_normalized_ip_distance_cpp(data, points, k, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_gpu_flat_cpp
List nn_faiss_gpu_flat_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self);
RcppExport SEXP _faissR_nn_faiss_gpu_flat_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_gpu_flat_cpp(data, points, k, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_gpu_flat_ip_cpp
List nn_faiss_gpu_flat_ip_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self);
RcppExport SEXP _faissR_nn_faiss_gpu_flat_ip_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_gpu_flat_ip_cpp(data, points, k, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_gpu_flat_normalized_ip_distance_cpp
List nn_faiss_gpu_flat_normalized_ip_distance_cpp(NumericMatrix data, NumericMatrix points, int k, bool exclude_self);
RcppExport SEXP _faissR_nn_faiss_gpu_flat_normalized_ip_distance_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_gpu_flat_normalized_ip_distance_cpp(data, points, k, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_ivfpq_cpp
List nn_faiss_ivfpq_cpp(NumericMatrix data, NumericMatrix points, int k, int nlist, int nprobe, int pq_m, int pq_nbits, std::string metric, std::string distance_output, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_ivfpq_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP nlistSEXP, SEXP nprobeSEXP, SEXP pq_mSEXP, SEXP pq_nbitsSEXP, SEXP metricSEXP, SEXP distance_outputSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nlist(nlistSEXP);
    Rcpp::traits::input_parameter< int >::type nprobe(nprobeSEXP);
    Rcpp::traits::input_parameter< int >::type pq_m(pq_mSEXP);
    Rcpp::traits::input_parameter< int >::type pq_nbits(pq_nbitsSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_output(distance_outputSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_ivfpq_cpp(data, points, k, nlist, nprobe, pq_m, pq_nbits, metric, distance_output, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_hnsw_cpp
List nn_faiss_hnsw_cpp(NumericMatrix data, NumericMatrix points, int k, int m, int ef_construction, int ef_search, std::string metric, std::string distance_output, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_hnsw_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP mSEXP, SEXP ef_constructionSEXP, SEXP ef_searchSEXP, SEXP metricSEXP, SEXP distance_outputSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type ef_construction(ef_constructionSEXP);
    Rcpp::traits::input_parameter< int >::type ef_search(ef_searchSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_output(distance_outputSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_hnsw_cpp(data, points, k, m, ef_construction, ef_search, metric, distance_output, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_nsg_cpp
List nn_faiss_nsg_cpp(NumericMatrix data, NumericMatrix points, int k, int r, int search_l, int build_type, std::string metric, std::string distance_output, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_nsg_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP rSEXP, SEXP search_lSEXP, SEXP build_typeSEXP, SEXP metricSEXP, SEXP distance_outputSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type search_l(search_lSEXP);
    Rcpp::traits::input_parameter< int >::type build_type(build_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_output(distance_outputSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_nsg_cpp(data, points, k, r, search_l, build_type, metric, distance_output, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_nndescent_cpp
List nn_faiss_nndescent_cpp(NumericMatrix data, NumericMatrix points, int k, int graph_k, int n_iter, int search_l, std::string metric, std::string distance_output, bool exclude_self, int n_threads);
RcppExport SEXP _faissR_nn_faiss_nndescent_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP graph_kSEXP, SEXP n_iterSEXP, SEXP search_lSEXP, SEXP metricSEXP, SEXP distance_outputSEXP, SEXP exclude_selfSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type graph_k(graph_kSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type search_l(search_lSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_output(distance_outputSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_nndescent_cpp(data, points, k, graph_k, n_iter, search_l, metric, distance_output, exclude_self, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_gpu_ivf_flat_cpp
List nn_faiss_gpu_ivf_flat_cpp(NumericMatrix data, NumericMatrix points, int k, int nlist, int nprobe, std::string metric, std::string distance_output, bool exclude_self);
RcppExport SEXP _faissR_nn_faiss_gpu_ivf_flat_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP nlistSEXP, SEXP nprobeSEXP, SEXP metricSEXP, SEXP distance_outputSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nlist(nlistSEXP);
    Rcpp::traits::input_parameter< int >::type nprobe(nprobeSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_output(distance_outputSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_gpu_ivf_flat_cpp(data, points, k, nlist, nprobe, metric, distance_output, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_gpu_ivfpq_cpp
List nn_faiss_gpu_ivfpq_cpp(NumericMatrix data, NumericMatrix points, int k, int nlist, int nprobe, int pq_m, int pq_nbits, std::string metric, std::string distance_output, bool exclude_self);
RcppExport SEXP _faissR_nn_faiss_gpu_ivfpq_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP nlistSEXP, SEXP nprobeSEXP, SEXP pq_mSEXP, SEXP pq_nbitsSEXP, SEXP metricSEXP, SEXP distance_outputSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nlist(nlistSEXP);
    Rcpp::traits::input_parameter< int >::type nprobe(nprobeSEXP);
    Rcpp::traits::input_parameter< int >::type pq_m(pq_mSEXP);
    Rcpp::traits::input_parameter< int >::type pq_nbits(pq_nbitsSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_output(distance_outputSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_gpu_ivfpq_cpp(data, points, k, nlist, nprobe, pq_m, pq_nbits, metric, distance_output, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// nn_faiss_gpu_cagra_cpp
List nn_faiss_gpu_cagra_cpp(NumericMatrix data, NumericMatrix points, int k, int graph_degree, int intermediate_graph_degree, int search_width, int itopk_size, bool exclude_self);
RcppExport SEXP _faissR_nn_faiss_gpu_cagra_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP graph_degreeSEXP, SEXP intermediate_graph_degreeSEXP, SEXP search_widthSEXP, SEXP itopk_sizeSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type graph_degree(graph_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type intermediate_graph_degree(intermediate_graph_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type search_width(search_widthSEXP);
    Rcpp::traits::input_parameter< int >::type itopk_size(itopk_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_faiss_gpu_cagra_cpp(data, points, k, graph_degree, intermediate_graph_degree, search_width, itopk_size, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// kmeans_faiss_cpp
List kmeans_faiss_cpp(NumericMatrix data, int centers, int max_iter, int nredo, double tol, int seed, int n_threads, bool kmeans_plus_plus);
RcppExport SEXP _faissR_kmeans_faiss_cpp(SEXP dataSEXP, SEXP centersSEXP, SEXP max_iterSEXP, SEXP nredoSEXP, SEXP tolSEXP, SEXP seedSEXP, SEXP n_threadsSEXP, SEXP kmeans_plus_plusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nredo(nredoSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type kmeans_plus_plus(kmeans_plus_plusSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans_faiss_cpp(data, centers, max_iter, nredo, tol, seed, n_threads, kmeans_plus_plus));
    return rcpp_result_gen;
END_RCPP
}
// kmeans_faiss_gpu_cpp
List kmeans_faiss_gpu_cpp(NumericMatrix data, int centers, int max_iter, int nredo, double tol, int seed, bool kmeans_plus_plus);
RcppExport SEXP _faissR_kmeans_faiss_gpu_cpp(SEXP dataSEXP, SEXP centersSEXP, SEXP max_iterSEXP, SEXP nredoSEXP, SEXP tolSEXP, SEXP seedSEXP, SEXP kmeans_plus_plusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nredo(nredoSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type kmeans_plus_plus(kmeans_plus_plusSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans_faiss_gpu_cpp(data, centers, max_iter, nredo, tol, seed, kmeans_plus_plus));
    return rcpp_result_gen;
END_RCPP
}
// sparse_nn_cpp
List sparse_nn_cpp(S4 data, S4 points, int k, std::string metric, bool exclude_self, bool self_query);
RcppExport SEXP _faissR_sparse_nn_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP metricSEXP, SEXP exclude_selfSEXP, SEXP self_querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type data(dataSEXP);
    Rcpp::traits::input_parameter< S4 >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< bool >::type self_query(self_querySEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_nn_cpp(data, points, k, metric, exclude_self, self_query));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_faissR_standardize_cpu_cpp", (DL_FUNC) &_faissR_standardize_cpu_cpp, 1},
    {"_faissR_strip_self_neighbors_cpp", (DL_FUNC) &_faissR_strip_self_neighbors_cpp, 2},
    {"_faissR_validate_projection_knn_cpp", (DL_FUNC) &_faissR_validate_projection_knn_cpp, 4},
    {"_faissR_mean_neighbor_rank_error_cpp", (DL_FUNC) &_faissR_mean_neighbor_rank_error_cpp, 3},
    {"_faissR_majority_vote_knn_labels_cpp", (DL_FUNC) &_faissR_majority_vote_knn_labels_cpp, 4},
    {"_faissR_batch_entropy_cpp", (DL_FUNC) &_faissR_batch_entropy_cpp, 4},
    {"_faissR_sampled_pair_distances_cpp", (DL_FUNC) &_faissR_sampled_pair_distances_cpp, 4},
    {"_faissR_knn_structure_score_cpp", (DL_FUNC) &_faissR_knn_structure_score_cpp, 6},
    {"_faissR_silhouette_score_cpp", (DL_FUNC) &_faissR_silhouette_score_cpp, 2},
    {"_faissR_interpolate_landmark_layout_cpp", (DL_FUNC) &_faissR_interpolate_landmark_layout_cpp, 5},
    {"_faissR_select_low_confidence_rows_cpp", (DL_FUNC) &_faissR_select_low_confidence_rows_cpp, 3},
    {"_faissR_project_embedding_knn_cpp", (DL_FUNC) &_faissR_project_embedding_knn_cpp, 3},
    {"_faissR_project_embedding_affine_cpp", (DL_FUNC) &_faissR_project_embedding_affine_cpp, 8},
    {"_faissR_project_embedding_affine_parallel_cpp", (DL_FUNC) &_faissR_project_embedding_affine_parallel_cpp, 9},
    {"_faissR_knn_graph_edges_cpp", (DL_FUNC) &_faissR_knn_graph_edges_cpp, 5},
    {"_faissR_cugraph_available_cpp", (DL_FUNC) &_faissR_cugraph_available_cpp, 0},
    {"_faissR_graph_cluster_cpp", (DL_FUNC) &_faissR_graph_cluster_cpp, 13},
    {"_faissR_graph_cluster_edges_cpp", (DL_FUNC) &_faissR_graph_cluster_edges_cpp, 9},
    {"_faissR_nn_cpp", (DL_FUNC) &_faissR_nn_cpp, 10},
    {"_faissR_nndescent_candidate_matrix_cpp", (DL_FUNC) &_faissR_nndescent_candidate_matrix_cpp, 3},
    {"_faissR_nndescent_candidate_matrix_adaptive_cpp", (DL_FUNC) &_faissR_nndescent_candidate_matrix_adaptive_cpp, 6},
    {"_faissR_nndescent_candidate_matrix_adaptive_subset_cpp", (DL_FUNC) &_faissR_nndescent_candidate_matrix_adaptive_subset_cpp, 5},
    {"_faissR_landmark_candidate_knn_cpp", (DL_FUNC) &_faissR_landmark_candidate_knn_cpp, 7},
    {"_faissR_landmark_candidate_knn_subset_cpp", (DL_FUNC) &_faissR_landmark_candidate_knn_subset_cpp, 8},
    {"_faissR_landmark_projection_knn_approx_cpp", (DL_FUNC) &_faissR_landmark_projection_knn_approx_cpp, 8},
    {"_faissR_nndescent_self_knn_cpp", (DL_FUNC) &_faissR_nndescent_self_knn_cpp, 10},
    {"_faissR_ivf_self_knn_cpp", (DL_FUNC) &_faissR_ivf_self_knn_cpp, 7},
    {"_faissR_annoy_self_knn_cpp", (DL_FUNC) &_faissR_annoy_self_knn_cpp, 8},
    {"_faissR_vptree_self_knn_cpp", (DL_FUNC) &_faissR_vptree_self_knn_cpp, 4},
    {"_faissR_vptree_query_knn_cpp", (DL_FUNC) &_faissR_vptree_query_knn_cpp, 5},
    {"_faissR_grid2d_self_knn_cpp", (DL_FUNC) &_faissR_grid2d_self_knn_cpp, 5},
    {"_faissR_grid3d_self_knn_cpp", (DL_FUNC) &_faissR_grid3d_self_knn_cpp, 5},
    {"_faissR_candidate_knn_cpp", (DL_FUNC) &_faissR_candidate_knn_cpp, 9},
    {"_faissR_cuda_available_cpp", (DL_FUNC) &_faissR_cuda_available_cpp, 0},
    {"_faissR_cuda_device_info_json_cpp", (DL_FUNC) &_faissR_cuda_device_info_json_cpp, 0},
    {"_faissR_nn_cuda_cpp", (DL_FUNC) &_faissR_nn_cuda_cpp, 4},
    {"_faissR_landmark_candidate_knn_cuda_cpp", (DL_FUNC) &_faissR_landmark_candidate_knn_cuda_cpp, 5},
    {"_faissR_row_candidate_knn_cuda_cpp", (DL_FUNC) &_faissR_row_candidate_knn_cuda_cpp, 4},
    {"_faissR_cuda_grid_self_knn_cpp", (DL_FUNC) &_faissR_cuda_grid_self_knn_cpp, 3},
    {"_faissR_cuvs_available_cpp", (DL_FUNC) &_faissR_cuvs_available_cpp, 0},
    {"_faissR_cuvs_info_json_cpp", (DL_FUNC) &_faissR_cuvs_info_json_cpp, 0},
    {"_faissR_nn_cuvs_bruteforce_cpp", (DL_FUNC) &_faissR_nn_cuvs_bruteforce_cpp, 4},
    {"_faissR_nn_cuvs_cagra_cpp", (DL_FUNC) &_faissR_nn_cuvs_cagra_cpp, 8},
    {"_faissR_nn_cuvs_nndescent_self_cpp", (DL_FUNC) &_faissR_nn_cuvs_nndescent_self_cpp, 5},
    {"_faissR_nn_cuvs_ivf_flat_cpp", (DL_FUNC) &_faissR_nn_cuvs_ivf_flat_cpp, 6},
    {"_faissR_nn_cuvs_ivf_pq_cpp", (DL_FUNC) &_faissR_nn_cuvs_ivf_pq_cpp, 8},
    {"_faissR_kmeans_cuvs_cpp", (DL_FUNC) &_faissR_kmeans_cuvs_cpp, 7},
    {"_faissR_faiss_available_cpp", (DL_FUNC) &_faissR_faiss_available_cpp, 0},
    {"_faissR_faiss_info_json_cpp", (DL_FUNC) &_faissR_faiss_info_json_cpp, 0},
    {"_faissR_nn_faiss_flat_cpp", (DL_FUNC) &_faissR_nn_faiss_flat_cpp, 5},
    {"_faissR_nn_faiss_flat_float32_cpp", (DL_FUNC) &_faissR_nn_faiss_flat_float32_cpp, 7},
    {"_faissR_nn_faiss_ivf_cpp", (DL_FUNC) &_faissR_nn_faiss_ivf_cpp, 9},
    {"_faissR_nn_faiss_flat_ip_cpp", (DL_FUNC) &_faissR_nn_faiss_flat_ip_cpp, 5},
    {"_faissR_nn_faiss_flat_normalized_ip_distance_cpp", (DL_FUNC) &_faissR_nn_faiss_flat_normalized_ip_distance_cpp, 5},
    {"_faissR_nn_faiss_gpu_flat_cpp", (DL_FUNC) &_faissR_nn_faiss_gpu_flat_cpp, 4},
    {"_faissR_nn_faiss_gpu_flat_ip_cpp", (DL_FUNC) &_faissR_nn_faiss_gpu_flat_ip_cpp, 4},
    {"_faissR_nn_faiss_gpu_flat_normalized_ip_distance_cpp", (DL_FUNC) &_faissR_nn_faiss_gpu_flat_normalized_ip_distance_cpp, 4},
    {"_faissR_nn_faiss_ivfpq_cpp", (DL_FUNC) &_faissR_nn_faiss_ivfpq_cpp, 11},
    {"_faissR_nn_faiss_hnsw_cpp", (DL_FUNC) &_faissR_nn_faiss_hnsw_cpp, 10},
    {"_faissR_nn_faiss_nsg_cpp", (DL_FUNC) &_faissR_nn_faiss_nsg_cpp, 10},
    {"_faissR_nn_faiss_nndescent_cpp", (DL_FUNC) &_faissR_nn_faiss_nndescent_cpp, 10},
    {"_faissR_nn_faiss_gpu_ivf_flat_cpp", (DL_FUNC) &_faissR_nn_faiss_gpu_ivf_flat_cpp, 8},
    {"_faissR_nn_faiss_gpu_ivfpq_cpp", (DL_FUNC) &_faissR_nn_faiss_gpu_ivfpq_cpp, 10},
    {"_faissR_nn_faiss_gpu_cagra_cpp", (DL_FUNC) &_faissR_nn_faiss_gpu_cagra_cpp, 8},
    {"_faissR_kmeans_faiss_cpp", (DL_FUNC) &_faissR_kmeans_faiss_cpp, 8},
    {"_faissR_kmeans_faiss_gpu_cpp", (DL_FUNC) &_faissR_kmeans_faiss_gpu_cpp, 7},
    {"_faissR_sparse_nn_cpp", (DL_FUNC) &_faissR_sparse_nn_cpp, 6},
    {NULL, NULL, 0}
};

void register_faissR_ccallables(DllInfo *dll);
RcppExport void R_init_faissR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    register_faissR_ccallables(dll);
}
