# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

standardize_cpu_cpp <- function(data) {
    .Call(`_faissR_standardize_cpu_cpp`, data)
}

strip_self_neighbors_cpp <- function(indices, distances) {
    .Call(`_faissR_strip_self_neighbors_cpp`, indices, distances)
}

validate_projection_knn_cpp <- function(indices, distances, n_reference, k) {
    .Call(`_faissR_validate_projection_knn_cpp`, indices, distances, n_reference, k)
}

mean_neighbor_rank_error_cpp <- function(high_indices, embed_indices, k) {
    .Call(`_faissR_mean_neighbor_rank_error_cpp`, high_indices, embed_indices, k)
}

knn_recall_cpp <- function(approx_indices, exact_indices, k) {
    .Call(`_faissR_knn_recall_cpp`, approx_indices, exact_indices, k)
}

majority_vote_knn_labels_cpp <- function(embed_indices, labels, k, n_label_levels) {
    .Call(`_faissR_majority_vote_knn_labels_cpp`, embed_indices, labels, k, n_label_levels)
}

batch_entropy_cpp <- function(embed_indices, batch, k, n_batch_levels) {
    .Call(`_faissR_batch_entropy_cpp`, embed_indices, batch, k, n_batch_levels)
}

sampled_pair_distances_cpp <- function(x, a, b, n_threads) {
    .Call(`_faissR_sampled_pair_distances_cpp`, x, a, b, n_threads)
}

knn_structure_score_cpp <- function(layout, indices, keep, preserve_k, labels, n_label_levels) {
    .Call(`_faissR_knn_structure_score_cpp`, layout, indices, keep, preserve_k, labels, n_label_levels)
}

silhouette_score_cpp <- function(layout, labels) {
    .Call(`_faissR_silhouette_score_cpp`, layout, labels)
}

interpolate_landmark_layout_cpp <- function(landmark_layout, landmark_indices, projection_indices, projection_distances, n) {
    .Call(`_faissR_interpolate_landmark_layout_cpp`, landmark_layout, landmark_indices, projection_indices, projection_distances, n)
}

select_low_confidence_rows_cpp <- function(confidence, landmark_indices, fraction) {
    .Call(`_faissR_select_low_confidence_rows_cpp`, confidence, landmark_indices, fraction)
}

project_embedding_knn_cpp <- function(reference_layout, projection_indices, projection_distances) {
    .Call(`_faissR_project_embedding_knn_cpp`, reference_layout, projection_indices, projection_distances)
}

project_embedding_affine_cpp <- function(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5) {
    .Call(`_faissR_project_embedding_affine_cpp`, reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation)
}

project_embedding_affine_parallel_cpp <- function(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5, n_threads = 1L) {
    .Call(`_faissR_project_embedding_affine_parallel_cpp`, reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation, n_threads)
}

knn_graph_edges_cpp <- function(indices, distances, weight_type, prune, mutual) {
    .Call(`_faissR_knn_graph_edges_cpp`, indices, distances, weight_type, prune, mutual)
}

graph_cluster_cpp <- function(indices, distances, method, backend, weight_type, prune, mutual, n_threads, n_runs, resolution, n_iterations, steps, seed) {
    .Call(`_faissR_graph_cluster_cpp`, indices, distances, method, backend, weight_type, prune, mutual, n_threads, n_runs, resolution, n_iterations, steps, seed)
}

graph_cluster_edges_cpp <- function(edge_list, method, backend, n_threads, n_runs, resolution, n_iterations, steps, seed) {
    .Call(`_faissR_graph_cluster_edges_cpp`, edge_list, method, backend, n_threads, n_runs, resolution, n_iterations, steps, seed)
}

nn_cpp <- function(data, points, k, method, square, sorted, p, parallel, cores, exclude_self) {
    .Call(`_faissR_nn_cpp`, data, points, k, method, square, sorted, p, parallel, cores, exclude_self)
}

nndescent_candidate_matrix_cpp <- function(indices, n_sources, n_neighbors) {
    .Call(`_faissR_nndescent_candidate_matrix_cpp`, indices, n_sources, n_neighbors)
}

nndescent_candidate_matrix_mlx_cpp <- function(indices, flags, n_sources, n_neighbors, use_reverse, active_only) {
    .Call(`_faissR_nndescent_candidate_matrix_mlx_cpp`, indices, flags, n_sources, n_neighbors, use_reverse, active_only)
}

nndescent_candidate_matrix_mlx_subset_cpp <- function(indices, flags, n_sources, n_neighbors, use_reverse) {
    .Call(`_faissR_nndescent_candidate_matrix_mlx_subset_cpp`, indices, flags, n_sources, n_neighbors, use_reverse)
}

landmark_candidate_knn_cpp <- function(data, projection_indices, k, bucket_cols, query_cols, parallel, cores) {
    .Call(`_faissR_landmark_candidate_knn_cpp`, data, projection_indices, k, bucket_cols, query_cols, parallel, cores)
}

landmark_candidate_knn_subset_cpp <- function(data, projection_indices, query_rows, k, bucket_cols, query_cols, parallel, cores) {
    .Call(`_faissR_landmark_candidate_knn_subset_cpp`, data, projection_indices, query_rows, k, bucket_cols, query_cols, parallel, cores)
}

landmark_projection_knn_approx_cpp <- function(landmarks, queries, k, n_projections, window, seed, parallel, cores) {
    .Call(`_faissR_landmark_projection_knn_approx_cpp`, landmarks, queries, k, n_projections, window, seed, parallel, cores)
}

nndescent_self_knn_cpp <- function(data, k, pool_size, n_iters, max_candidates, n_random_projections, seed, parallel, cores) {
    .Call(`_faissR_nndescent_self_knn_cpp`, data, k, pool_size, n_iters, max_candidates, n_random_projections, seed, parallel, cores)
}

ivf_self_knn_cpp <- function(data, k, nlist, nprobe, seed, parallel, cores) {
    .Call(`_faissR_ivf_self_knn_cpp`, data, k, nlist, nprobe, seed, parallel, cores)
}

annoy_self_knn_cpp <- function(data, k, n_trees, leaf_size, search_k, seed, parallel, cores) {
    .Call(`_faissR_annoy_self_knn_cpp`, data, k, n_trees, leaf_size, search_k, seed, parallel, cores)
}

vptree_self_knn_cpp <- function(data, k, parallel, cores) {
    .Call(`_faissR_vptree_self_knn_cpp`, data, k, parallel, cores)
}

vptree_query_knn_cpp <- function(data, points, k, parallel, cores) {
    .Call(`_faissR_vptree_query_knn_cpp`, data, points, k, parallel, cores)
}

grid2d_self_knn_cpp <- function(data, k, parallel, cores, bins_per_dim) {
    .Call(`_faissR_grid2d_self_knn_cpp`, data, k, parallel, cores, bins_per_dim)
}

grid3d_self_knn_cpp <- function(data, k, parallel, cores, bins_per_dim) {
    .Call(`_faissR_grid3d_self_knn_cpp`, data, k, parallel, cores, bins_per_dim)
}

candidate_knn_cpp <- function(data, points, candidate_indices, k, method, square, exclude_self, parallel, cores) {
    .Call(`_faissR_candidate_knn_cpp`, data, points, candidate_indices, k, method, square, exclude_self, parallel, cores)
}

cuda_available_cpp <- function() {
    .Call(`_faissR_cuda_available_cpp`)
}

cuda_device_info_json_cpp <- function() {
    .Call(`_faissR_cuda_device_info_json_cpp`)
}

nn_cuda_cpp <- function(data, points, k, square) {
    .Call(`_faissR_nn_cuda_cpp`, data, points, k, square)
}

landmark_candidate_knn_cuda_cpp <- function(data, projection_indices, k, bucket_cols, query_cols) {
    .Call(`_faissR_landmark_candidate_knn_cuda_cpp`, data, projection_indices, k, bucket_cols, query_cols)
}

row_candidate_knn_cuda_cpp <- function(data, candidate_indices, k) {
    .Call(`_faissR_row_candidate_knn_cuda_cpp`, data, candidate_indices, k)
}

cuda_grid_self_knn_cpp <- function(data, k, bins_per_dim) {
    .Call(`_faissR_cuda_grid_self_knn_cpp`, data, k, bins_per_dim)
}

cuvs_available_cpp <- function() {
    .Call(`_faissR_cuvs_available_cpp`)
}

cuvs_info_json_cpp <- function() {
    .Call(`_faissR_cuvs_info_json_cpp`)
}

nn_cuvs_bruteforce_cpp <- function(data, points, k, exclude_self) {
    .Call(`_faissR_nn_cuvs_bruteforce_cpp`, data, points, k, exclude_self)
}

nn_cuvs_cagra_cpp <- function(data, points, k, exclude_self, graph_degree, intermediate_graph_degree, search_width, itopk_size) {
    .Call(`_faissR_nn_cuvs_cagra_cpp`, data, points, k, exclude_self, graph_degree, intermediate_graph_degree, search_width, itopk_size)
}

nn_cuvs_nndescent_self_cpp <- function(data, k, graph_degree, intermediate_graph_degree, max_iterations) {
    .Call(`_faissR_nn_cuvs_nndescent_self_cpp`, data, k, graph_degree, intermediate_graph_degree, max_iterations)
}

nn_cuvs_ivf_flat_cpp <- function(data, points, k, n_lists, n_probes, exclude_self) {
    .Call(`_faissR_nn_cuvs_ivf_flat_cpp`, data, points, k, n_lists, n_probes, exclude_self)
}

nn_cuvs_ivf_pq_cpp <- function(data, points, k, n_lists, n_probes, pq_dim, pq_bits, exclude_self) {
    .Call(`_faissR_nn_cuvs_ivf_pq_cpp`, data, points, k, n_lists, n_probes, pq_dim, pq_bits, exclude_self)
}

kmeans_cuvs_cpp <- function(data, centers, max_iter, n_init, tol, streaming_batch_size, kmeans_plus_plus) {
    .Call(`_faissR_kmeans_cuvs_cpp`, data, centers, max_iter, n_init, tol, streaming_batch_size, kmeans_plus_plus)
}

faiss_available_cpp <- function() {
    .Call(`_faissR_faiss_available_cpp`)
}

faiss_info_json_cpp <- function() {
    .Call(`_faissR_faiss_info_json_cpp`)
}

nn_faiss_flat_cpp <- function(data, points, k, exclude_self, n_threads) {
    .Call(`_faissR_nn_faiss_flat_cpp`, data, points, k, exclude_self, n_threads)
}

nn_faiss_ivf_cpp <- function(data, points, k, nlist, nprobe, exclude_self, n_threads) {
    .Call(`_faissR_nn_faiss_ivf_cpp`, data, points, k, nlist, nprobe, exclude_self, n_threads)
}

nn_faiss_flat_ip_cpp <- function(data, points, k, exclude_self, n_threads) {
    .Call(`_faissR_nn_faiss_flat_ip_cpp`, data, points, k, exclude_self, n_threads)
}

nn_faiss_gpu_flat_cpp <- function(data, points, k, exclude_self) {
    .Call(`_faissR_nn_faiss_gpu_flat_cpp`, data, points, k, exclude_self)
}

nn_faiss_gpu_flat_ip_cpp <- function(data, points, k, exclude_self) {
    .Call(`_faissR_nn_faiss_gpu_flat_ip_cpp`, data, points, k, exclude_self)
}

nn_faiss_ivfpq_cpp <- function(data, points, k, nlist, nprobe, pq_m, pq_nbits, exclude_self, n_threads) {
    .Call(`_faissR_nn_faiss_ivfpq_cpp`, data, points, k, nlist, nprobe, pq_m, pq_nbits, exclude_self, n_threads)
}

nn_faiss_hnsw_cpp <- function(data, points, k, m, ef_construction, ef_search, exclude_self, n_threads) {
    .Call(`_faissR_nn_faiss_hnsw_cpp`, data, points, k, m, ef_construction, ef_search, exclude_self, n_threads)
}

nn_faiss_nsg_cpp <- function(data, points, k, r, search_l, build_type, exclude_self, n_threads) {
    .Call(`_faissR_nn_faiss_nsg_cpp`, data, points, k, r, search_l, build_type, exclude_self, n_threads)
}

nn_faiss_nndescent_cpp <- function(data, points, k, graph_k, n_iter, search_l, exclude_self, n_threads) {
    .Call(`_faissR_nn_faiss_nndescent_cpp`, data, points, k, graph_k, n_iter, search_l, exclude_self, n_threads)
}

nn_faiss_gpu_ivf_flat_cpp <- function(data, points, k, nlist, nprobe, exclude_self) {
    .Call(`_faissR_nn_faiss_gpu_ivf_flat_cpp`, data, points, k, nlist, nprobe, exclude_self)
}

nn_faiss_gpu_ivfpq_cpp <- function(data, points, k, nlist, nprobe, pq_m, pq_nbits, exclude_self) {
    .Call(`_faissR_nn_faiss_gpu_ivfpq_cpp`, data, points, k, nlist, nprobe, pq_m, pq_nbits, exclude_self)
}

nn_faiss_gpu_cagra_cpp <- function(data, points, k, graph_degree, intermediate_graph_degree, search_width, itopk_size, exclude_self) {
    .Call(`_faissR_nn_faiss_gpu_cagra_cpp`, data, points, k, graph_degree, intermediate_graph_degree, search_width, itopk_size, exclude_self)
}

kmeans_faiss_cpp <- function(data, centers, max_iter, nredo, tol, seed, n_threads, kmeans_plus_plus) {
    .Call(`_faissR_kmeans_faiss_cpp`, data, centers, max_iter, nredo, tol, seed, n_threads, kmeans_plus_plus)
}

kmeans_faiss_gpu_cpp <- function(data, centers, max_iter, nredo, tol, seed, kmeans_plus_plus) {
    .Call(`_faissR_kmeans_faiss_gpu_cpp`, data, centers, max_iter, nredo, tol, seed, kmeans_plus_plus)
}

sparse_nn_cpp <- function(data, points, k, metric, exclude_self, self_query) {
    .Call(`_faissR_sparse_nn_cpp`, data, points, k, metric, exclude_self, self_query)
}

